### ISSUE TITLE
service exception in log

### ISSUE THREAD

**Issue by cdivvela** [ChandraAddala/taskatomic-svc#6]
11:55:10.735 [qtp1006485584-15] ERROR c.t.svc.controller.AppController - Request failed with exception
java.lang.NumberFormatException: For input string: "spacex-landing-pad"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_25]
    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.StringOps.toInt(StringOps.scala:31) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController$$anonfun$7.apply(AppController.scala:56) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$json$JsonSupport$$super$invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.Option.flatMap(Option.scala:170) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.Stream.flatMap(Stream.scala:446) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$scalate$ScalateSupport$$super$handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.scalate.ScalateSupport$class.handle(ScalateSupport.scala:130) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54) [services-1.0-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539) [services-1.0-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
11:56:37.954 [qtp1006485584-13] ERROR c.t.svc.controller.AppController - Request failed with exception
java.lang.NumberFormatException: For input string: "spacex-landing-pad"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_25]
    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.StringOps.toInt(StringOps.scala:31) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController$$anonfun$7.apply(AppController.scala:56) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$json$JsonSupport$$super$invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.Option.flatMap(Option.scala:170) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.Stream.flatMap(Stream.scala:446) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$scalate$ScalateSupport$$super$handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.scalate.ScalateSupport$class.handle(ScalateSupport.scala:130) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54) [services-1.0-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539) [services-1.0-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
12:15:52.494 [qtp1006485584-11] ERROR c.t.svc.controller.AppController - Request failed with exception
java.lang.NumberFormatException: For input string: "spacex-landing-pad"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_25]
    at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_25]
    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.StringOps.toInt(StringOps.scala:31) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController$$anonfun$7.apply(AppController.scala:56) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$json$JsonSupport$$super$invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.withRouteMultiParams(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68) ~[services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.invoke(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.Option.flatMap(Option.scala:170) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237) ~[services-1.0-SNAPSHOT.jar:na]
    at scala.collection.immutable.Stream.flatMap(Stream.scala:446) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175) ~[services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60) [services-1.0-SNAPSHOT.jar:na]
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.org$scalatra$scalate$ScalateSupport$$super$handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.scalate.ScalateSupport$class.handle(ScalateSupport.scala:130) [services-1.0-SNAPSHOT.jar:na]
    at com.taskatomic.svc.controller.AppController.handle(AppController.scala:14) [services-1.0-SNAPSHOT.jar:na]
    at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54) [services-1.0-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:497) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610) [services-1.0-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539) [services-1.0-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by ChandraAddala** [comment]
You have to use project id, not project name in your url. /users/cdivvela/projects/1

Even for tasks you have to use task id, /users/cdivvela/projects/1/tasks/1
